core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include

from pwn_event.views.n8n import n8n_json_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('evenements/', include('pwn_event.urls')),
    path('last-event/', n8n_json_view, name='get-last-event-json'),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    re_path(r'^', include('cms.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pwn_event/models/event.py
# -*- coding: utf-8 -*-
""" Event model for Creation """

from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.utils.timezone import now

from django_extensions.db.fields import AutoSlugField
from filer.fields.image import FilerImageField
# from ckeditor.fields import RichTextField
from django_ckeditor_5.fields import CKEditor5Field as RichTextField

from ..models.place import Place
from ..models.speaker import Speaker
from ..models.season import Season
from ..models.tag import Tag
from ..managers import EventPublishedManager
from ..utils import get_or_create_season


class Event(models.Model):
    """ """
    title = models.CharField(_('title'), max_length=250)
    slug = AutoSlugField(_('slug'), max_length=255, populate_from=['title'], unique=True, db_index=True)
    image = FilerImageField(default=None, verbose_name=_("image"), null=True, blank=True, on_delete=models.SET_NULL)
    excerpt = RichTextField(_('excerpt'), blank=True, null=True)
    description = RichTextField(_('description'), blank=True, null=True)
    place = models.ForeignKey(Place, on_delete=models.SET_NULL, verbose_name=_('place'), related_name="events",
                              null=True, blank=True)
    speakers = models.ManyToManyField(Speaker, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    date = models.DateTimeField(_('Event date'))
    season = models.ForeignKey(Season, on_delete=models.PROTECT,
                               verbose_name=_('season'), related_name="events", null=True, blank=True)

    n8n = models.BooleanField(_('n8n'), default=True, help_text="La conférence est-elle visible par n8n ?")
    is_publish = models.BooleanField(_('is publish'), default=False)
    start_publication = models.DateTimeField(_('start publication'), blank=True, null=True,
                                             help_text=_('Start date of publication.'))
    end_publication = models.DateTimeField(_('end publication'), blank=True, null=True,
                                           help_text=_('End date of publication.'))

    objects = models.Manager()
    published = EventPublishedManager()

    class Meta:
        get_latest_by = '-date'
        verbose_name = _('Event')
        verbose_name_plural = _('Events')
        ordering = ('-date', )

    def __str__(self):
        return f"{self.date} : {self.title}"

    def get_absolute_url(self):
        """
        Builds and returns the category's URL
        based on his tree path.
        """
        return reverse('pwn_event:event_detail', kwargs={'slug': self.slug})

    def is_passed(self):
        """ Check if the event is passed """
        last_event_time = now().replace(hour=00, minute=00, second=00) # todo : utilisé à plusieurs endroitn faire une fonction
        if self.date <= last_event_time:
            return True
        return False

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        season = get_or_create_season(self.date)
        self.season = season

        super().save(force_insert, force_update, using, update_fields)

pwn_event/models/place.py
# -*- coding: utf-8 -*-
""" Event model for Creation """

from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

from django_extensions.db.fields import AutoSlugField
from filer.fields.image import FilerImageField
from ckeditor.fields import RichTextField


class Place(models.Model):
    """ """
    name = models.CharField(_('name'), max_length=250, unique=True)
    slug = AutoSlugField(_('slug'), max_length=255, populate_from=['name'], unique=True, db_index=True)
    image = FilerImageField(default=None, verbose_name=_("image"), null=True, blank=True, on_delete=models.SET_NULL)
    description = RichTextField(_('biography'), blank=True, null=True)
    address = models.CharField(_('address'), max_length=250, null=True, blank=True)
    address2 = models.CharField(_('address complement'), max_length=250, null=True, blank=True)
    zip = models.CharField(_('zip'), max_length=250, null=True, blank=True)
    city = models.CharField(_('city'), max_length=250, null=True, blank=True)
    url = models.URLField(_('external link'), max_length=250, null=True, blank=True)

    def __str__(self):
        return self.name

    @property
    def get_address(self):
        address = self.address if self.address else ''
        address2 = f" {self.address2}" if self.address2 else ''
        zipcode = f"{self.zip} " if self.zip else ''
        city = self.city if self.city else ''

        address_str = f"{self.name}, {address}{address2}"
        if zipcode or city:
            address_str += f", {zipcode}{city}"

        return address_str

    class Meta:
        verbose_name = _('Place')
        verbose_name_plural = _('Places')

    def get_absolute_url(self):
        """
        Builds and returns the category's URL
        based on his tree path.
        """
        return reverse('pwn_event:place_detail', kwargs={'slug': self.slug})

pwn_event/models/speaker.py
# -*- coding: utf-8 -*-
""" Event model for Creation """

from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

from django_extensions.db.fields import AutoSlugField
from filer.fields.image import FilerImageField
# from ckeditor.fields import RichTextField
from django_ckeditor_5.fields import CKEditor5Field as RichTextField

class Speaker(models.Model):
    """ """
    last_name = models.CharField(_('last name'), max_length=250)
    first_name = models.CharField(_('first name'), max_length=250)
    slug = AutoSlugField(_('slug'), max_length=255, populate_from=['last_name', 'first_name'], unique=True, db_index=True)
    image = FilerImageField(default=None, verbose_name=_("image"), null=True, blank=True, on_delete=models.SET_NULL)
    biography = RichTextField(_('biography'), blank=True, null=True)
    url = models.URLField(_('external link'), max_length=250, null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    class Meta:
        verbose_name = _('Speaker')
        verbose_name_plural = _('Speakers')

    def get_absolute_url(self):
        """
        Builds and returns the speaker's URL based on his detail path.
        """
        return reverse('pwn_event:speaker_detail', kwargs={'slug': self.slug})

pwn_event/views/event.py
# -*- coding: utf-8 -*-
""" PWN Event: event view """
from datetime import timedelta

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.utils.timezone import now

from ..models.event import Event
from ..models.season import Season
from ..app_settings import PAGINATION


class EventListView(ListView):
    """ """
    model = Event
    context_object_name = "event_list"


class EventBySeasonListView(ListView):
    """ """
    template_name = 'pwn_event/event_season_list.html'
    context_object_name = "events"

    def __init__(self):
        self.season = None

    def get_queryset(self, **kwargs):
        try:
            self.season = Season.objects.get(start_date__lte=now(), end_date__gte=now())
        except Season.DoesNotExist:
            self.season = None
        last_event_time = now().replace(hour=00, minute=00, second=00)
        if self.request.user.is_superuser:
            return Event.objects.filter(season=self.season, date__gte=last_event_time)
        return Event.published.filter(season=self.season, date__gte=last_event_time)

    def get_context_data(self, **kwargs):
        context = super(EventBySeasonListView, self).get_context_data(**kwargs)
        context['actual_season'] = self.season
        try:
            context["futur_season"] = Season.objects.get(
                start_date__year=now().year, start_date__month=9
            )
            context["futur_events"] = Event.objects.filter(
                season=context["futur_season"]
            )
        except Season.DoesNotExist:
            context["futur_season"] = None
            context["futur_events"] = None

        try:
            past_seasons = Season.objects.filter(start_date__lte=now())
        except Season.DoesNotExist:
            past_seasons = None

        context['past_seasons'] = past_seasons
        return context


class EventDetailView(DetailView):
    """ """
    model = Event
    context_object_name = "event"
    paginate_by = PAGINATION

    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_superuser:
            return Event.objects.filter()
        return Event.published.filter()

templates/back.aldryn_events/includes/calendar.html
{% load i18n static aldryn_events sekizai_tags %}

{% block events_calendar %}
    {% if namespace_error %}
        {% if request.user.is_staff or request.user.is_superuser %}
            <p>{{ namespace_error }}</p>
        {% endif %}
    {% else %}
        <div id="js-calendar-{{ plugin.instance.pk }}"
            data-url="{% fallback_aware_namespace_url 'get-calendar-dates' calendar_tag.namespace %}"
            data-pk="{{ plugin.instance.pk }}"
            data-error="{% trans 'There was a problem accessing the calendar, please try again.'|escapejs %}">

            <h3>{{ calendar_tag.label }}</h3>
            <p>
                <a href="#" class="js-calendar-trigger" data-direction="previous">{% trans "Previous month" %}</a>
                <a href="{% fallback_aware_namespace_url 'events_list' calendar_tag.namespace %}">{% trans "Today" %}</a>
                <a href="#" class="js-calendar-trigger" data-direction="next">{% trans "Next month" %}</a>
            </p>

            {% include "back.aldryn_events/includes/calendar_table.html" %}
        </div>
    {% endif %}
{% endblock %}

{% addtoblock "js" %}
<script>
jQuery(document).ready(function ($) {
    $('#js-calendar-{{ plugin.instance.pk }}').on('click', '.js-calendar-trigger', function (e) {
        e.preventDefault();

        var calendar = $(e.delegateTarget);
        var settings = calendar.data();
        var direction = $(this).data('direction');
        var table = calendar.find('.js-calendar-table');
        var month = parseInt(table.data('month-numeric'));
        var year = parseInt(table.data('year'));
        var title = calendar.find('h3');

        // cancel if no direction is provided
        if (!direction) {
            return false;
        }

        // handle first and last bound
        if (direction === 'next') {
            if (month === 12) {
                month = 1;
                year += 1;
            } else {
                month += 1;
            }
        }
        if (direction === 'previous') {
            if (month === 1) {
                month = 12;
                year -= 1;
            } else {
                month -= 1;
            }
        }

        // send proper ajax request
        $.ajax({
            type: 'get',
            url: settings.url + year + '/' + month + '/?plugin_pk=' + settings.pk,
            success: function (data) {
                table.replaceWith(data);
                title.html($(data).data('month') + ' ' + $(data).data('year'));
            },
            error: function () {
                alert(settings.error);
            }
        });
    });
});
</script>
{% endaddtoblock %}

templates/back.aldryn_events/includes/calendar_table.html
{% load i18n aldryn_events %}

{% spaceless %}
    <table class="js-calendar-table"
        data-month-numeric="{{ calendar_tag.current_date|date:'n' }}"
        data-month="{{ calendar_tag.current_date|date:'F' }}"
        data-year="{{ calendar_tag.current_date|date:'Y' }}">

        <tr class="header">
            <th>{% trans "Mo" %}</th>
            <th>{% trans "Tu" %}</th>
            <th>{% trans "We" %}</th>
            <th>{% trans "Th" %}</th>
            <th>{% trans "Fr" %}</th>
            <th class="weekend">{% trans "Sa" %}</th>
            <th class="weekend">{% trans "Su" %}</th>
        </tr>
        <tr>
            {% for day, events, css_classes in calendar_tag.calendar %}
            {% if forloop.counter0 != 0 and forloop.counter0|divisibleby:'7' %}
        </tr>
        <tr>
            {% endif %}
                <td{% if css_classes %} class="{{ css_classes }}"{% endif %}>
                {% if events %}
                    <a href="{% fallback_aware_namespace_url 'events_list-by-day' calendar_tag.namespace year=day|date:'Y' month=day|date:'n' day=day|date:'j'  %}">{{ day|date:'d' }}</a>
                {% else %}
                    <span>{{ day|date:'d' }}</span>
                {% endif %}
            </td>
            {% endfor %}
        </tr>
    </table>
{% endspaceless %}

templates/back.aldryn_events/includes/pagination.html
{% load i18n %}

<ul>
    {% if page_obj.has_previous %}
        <li>
            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">
                {% trans "Previous" %}
            </a>
        </li>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if num %}
            {% if page_obj.number == num %}
                <li class="active"><span>{{ num }}</span></li>
            {% else %}
                <li><a href="{{ request.path }}?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% else %}
            <li><a href="{{ request.path }}?page={{ num|add:"5" }}">...</a></li>
        {% endif %}
    {% empty %}
        <li class="active"><span>1</span></li>
    {% endfor %}

    {% if page_obj.has_next %}
        <li>
            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">
                {% trans "Next" %}
            </a>
        </li>
    {% endif %}
</ul>

templates/back.aldryn_events/includes/registration.html
{% load i18n cms_tags sekizai_tags apphooks_config_tags bootstrap3 %}

{# INFO: shown when registration is closed #}
{% if event.is_registration_deadline_passed %}
    <p>{% trans "The registration deadline for this event has passed, registration is closed." %}</p>
{% endif %}

{# INFO: shown when successfully registered #}
{% if already_registered and not event.is_registration_deadline_passed %}
    <p>{% trans "Thank you for your registration!" %}</p>
    <form class="form-custom" action="{% namespace_url 'events_registration_reset' event.slug namespace=view.namespace %}" method="post">
        {% csrf_token %}
        <button type="submit" class="button">{% trans "Reset your registration" %}</button>
    </form>
{% endif %}

{# INFO: shown when registration is open #}
{% if not already_registered and not event.is_registration_deadline_passed %}
    <form method="post" class="form-custom">
      <h3>Formulaire de réservation</h3>
        {% csrf_token %}

        {# --- Erreurs globales --- #}
        {{ form.non_field_errors }}


        {{ form.first_name.errors }}
        <label for="{{ form.first_name.id_for_label }}">Prénom</label>
        {{ form.first_name }}
        <!-- Je t'ai mis l'equivalent html en commentaire si tu souhaites ajouter un placeholder dans le champ ou un required par exemple-->
        {# <input id="id_first_name" maxlength="100" name="first_name" type="text">#}

        {{ form.last_name.errors }}
        <label for="{{ form.last_name.id_for_label }}">Nom</label>
        {{ form.last_name }}
        {# <input id="id_last_name" maxlength="100" name="last_name" type="text">#}

        {{ form.address.errors }}
        <label for="{{ form.address.id_for_label }}">Adresse</label>
        {{ form.address }}
        {# <textarea cols="40" id="id_address" name="address" rows="1"></textarea>#}


        {{ form.address_city.errors }}
        <label for="{{ form.address_city.id_for_label }}">Ville</label>
        {{ form.address_city }}
        {# <input id="id_address_city" maxlength="100" name="address_city" type="text">#}


        {{ form.mobile.errors }}
        <label for="{{ form.mobile.id_for_label }}">mobile</label>
        {{ form.mobile }}
        {# <input id="id_mobile" maxlength="20" name="mobile" type="text">#}

         {{ form.email.errors }}
        <label for="{{ form.email.id_for_label }}">email</label>
        {{ form.email }}
        {# <input id="id_email" maxlength="254" name="email" type="email">#}

        {{ form.message.errors }}
        <label for="{{ form.message.id_for_label }}">message</label>
        {{ form.message }}
        {# <textarea cols="40" id="id_message" name="message" rows="5"></textarea>#}

        <button type="submit" class="button">Réserver ma place pour cette conférence !</button>
    </form>
{% endif %}